### ISSUE TITLE
Search no longer accessible

### ISSUE THREAD

**Issue by dyraig** [DylanVanAssche/harbour-sailbook#88]
1. **What happens**: 
    - When hitting the Search button, I only get a message "The link you followed may be broken, or the page may have been removed". The only available option is to go to the News Feed. Until a couple of days ago, the error message mentioned above was shown, but together with a search field - that field is gone (probably due to some changes at Facebook)
    
2. **What was expected**:
    - The Search button leads to the search. 

3. **How to reproduce**: 
    1. Hit the Search button

4. **Environment**: 
    - Sailbook 11.0-3
    - Sailfish OS version: 3.0.1.11
    - Sailfish OS hardware: Jolla 1

**Comment by DylanVanAssche** [comment]
Hmmm that was the workaround that fixed that page.
We tricked FB to show the search by going to a 404 page. I spend hours to find the real page, but they make it very difficult to do that. FB doesn't like these webview clients since they sandbox them.

However, I just tried it on my device. I still have the search bar.
Suggestion: Try again a couple of times. Sometimes, FB disables stuff for some users and they come back after a couple of days/weeks. They use us as lab rats or something?

**Comment by dyraig** [comment]
Well, up until now not change, I'm afraid...

![photo_2019-05-29_21-17-22](https://user-images.githubusercontent.com/19952060/58585055-fa9efd80-8257-11e9-8b08-6477d65f3f7f.jpg)

**Comment by DylanVanAssche** [comment]
You have definitely a different page than I.
I just checked it again, the thumb design is different, I have also a bar with: `All`, `Photos`, `People`, ... and above that: `Search`.

**Comment by dyraig** [comment]
The thumb design changes almost every time I call that page (at least the colour of the plaster does) - but it did that before already, when the page I'm getting still had the bar you describe and search.

**Comment by dyraig** [comment]
Well, I'll be... ...today, the search behaviour reverted back to what it was before, i.e. the "page not found" plus the search bar. I have no idea what Facebook is busy with...

**Comment by DylanVanAssche** [comment]
Typically FB...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ghost** [comment]
Should be fixed on next update.
